name: Jobstreet Scraper

on:
  schedule:
  - cron: '30 */6 * * *'
  workflow_dispatch:       # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decode Google credentials JSON
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIAL_JSON }}" | base64 --decode > credentials.json

      - name: Run scraper
        env:
          GOOGLE_APPLICATION_CREDENTIALS: credentials.json
        run: |
          python main.py
