name: Jobstreet Scraper

on:
  schedule:
    - cron: '0 3 * * *'   # Runs daily at 3:00 UTC (~8:30 AM IST)
  workflow_dispatch:       # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python gsheet.py
